# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HackRF.net
email: scateu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        A blog about opensource SDR.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hackrf.net" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

# _pages
include: ['_pages']

imageurl: "https://raw.githubusercontent.com/scateu/hackrf.net/master/images"
